New-ADOrganizationalUnit -Name "Recursos Humanos" -Path "DC=Proyecto,DC=local"
New-ADOrganizationalUnit -Name "Explotacion" -Path "DC=Proyecto,DC=local"
New-ADOrganizationalUnit -Name "Marketing" -Path "DC=Proyecto,DC=local"
New-ADOrganizationalUnit -Name "Ventas" -Path "DC=Proyecto,DC=local"
New-ADOrganizationalUnit -Name "Desarrollo" -Path "DC=Proyecto,DC=local"
